[project]
name = "dl-animal-10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "kagglehub>=0.3.12",
    "lab>=8.4",
    "torch>=2.7.1",
    "torch-directml",
    "torchvision>=0.22.1",
]
