channels:
- conda-forge
dependencies:
- python=3.12.3
- pip
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - numpy==2.3.0
  - pandas==2.3.0
  - torch==2.7.1
  - torchvision==0.22.1
  - tqdm==4.67.1
name: mlflow-env
